DEVICE_NAME            : "Focusrite Scarlett 4i4"
pcm_id                 : "hw:1,0"
pcm_frames             : 50
pcm_sampleRate         : 96000
pcm_available_channels : 1
pcm_bits               : 32    
msg_length             : 0.1
