DEVICE_NAME            : "Focusrite Scarlett 4i4"
pcm_id                 : "hw:1,0"
pcm_frames             : 200
pcm_sampleRate         : 192000
pcm_available_channels : 2
pcm_bits               : 32    
msg_length             : 0.1
